### ISSUE TITLE
Create Sequence Diagram and upload to Wiki

### ISSUE THREAD

**Issue by PumpkinKing93** [CSCI-150-SCRUM/SCRUM-150#12]
The system shall have the ability for a user to create permissions for Users / Groups:
Guest – Read Only
i. Ability to View all Projects, Stories, Tasks List but no access to modify.

**Comment by kristenlabrie** [comment]
![scrum sequence 1](https://user-images.githubusercontent.com/35746649/49612344-5055b580-f959-11e8-87f4-99405ad9a6b1.jpeg)
