### ISSUE TITLE
Use case Diagram created and added to Wiki 

### ISSUE THREAD

**Issue by PumpkinKing93** [CSCI-150-SCRUM/SCRUM-150#23]
The system shall have the ability for the user to create a Task List.

**Comment by PumpkinKing93** [comment]
The use case diagram has been created and added to the wiki page on GitHub.

**Comment by kristenlabrie** [comment]
![scrum diagram](https://user-images.githubusercontent.com/35746649/49612376-6b282a00-f959-11e8-9f4d-cd614f49bdc4.jpeg)
