### ISSUE TITLE
Boards page

### ISSUE THREAD

**Issue by PumpkinKing93** [CSCI-150-SCRUM/SCRUM-150#36]
The system shall have the appropriate format in place to allow access from various mediums.
a. This is to include:
i. Tablet
ii. PC
iii. Mobile Phone (iOS and Android)

**Comment by PumpkinKing93** [comment]
The boards page has been created and has a field to connect to the DB. Currently doesn't connect.

**Comment by kristenlabrie** [comment]
Formatted boards page with different columns for each status of tasks
